### ISSUE TITLE
BoatSpringTemplatesTests fails on Windows OS

### ISSUE THREAD

**Issue by walaniam** [Backbase/backbase-openapi-tools#600]
When running `BoatSpringTemplatesTests` on Windows OS it fails with StackOverflowError. This issue is related to https://github.com/swagger-api/swagger-parser/issues/1886 , tested with proposed fix: https://github.com/swagger-api/swagger-parser/pull/1959

```java
java.lang.StackOverflowError
	at java.base/java.lang.StringLatin1.replace(StringLatin1.java:344)
	at java.base/java.lang.String.replace(String.java:2970)
	at org.openapitools.codegen.utils.ModelUtils.getSimpleRef(ModelUtils.java:401)
	at org.openapitools.codegen.utils.ModelUtils.getReferencedSchema(ModelUtils.java:802)
	at org.openapitools.codegen.DefaultCodegen.recursiveGetDiscriminator(DefaultCodegen.java:3237)
	at org.openapitools.codegen.DefaultCodegen.recursiveGetDiscriminator(DefaultCodegen.java:3252)
```

```java
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.backbase.oss.codegen.java.BoatSpringTemplatesTests.invoke(BoatSpringTemplatesTests.java:159)
	at com.backbase.oss.codegen.java.BoatSpringTemplatesTests.lambda$testStream$3(BoatSpringTemplatesTests.java:154)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.files" is null
	at com.backbase.oss.codegen.java.BoatSpringTemplatesTests.findPattern(BoatSpringTemplatesTests.java:228)
	at com.backbase.oss.codegen.java.BoatSpringTemplatesTests.useLombokAnnotations(BoatSpringTemplatesTests.java:211)
	... 26 more

```

**Comment by walaniam** [comment]
Fixed in https://github.com/swagger-api/swagger-parser/pull/2064
